// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ClearSessionizeCacheData, ClearSessionizeCacheErrors, ClearSessionizeCacheResponses, CreateBlogArticleData, CreateBlogArticleErrors, CreateBlogArticleResponses, IsBlogNodeData, IsBlogNodeErrors, IsBlogNodeResponses, RegenerateData, RegenerateErrors, RegenerateResponses, StatusData, StatusErrors, StatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoCommunityExtensionsService {
    public static createBlogArticle<ThrowOnError extends boolean = false>(options: Options<CreateBlogArticleData, ThrowOnError>) {
        return (options.client ?? client).post<CreateBlogArticleResponses, CreateBlogArticleErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/blog/{blogNodeKey}/create-article',
            ...options
        });
    }
    
    public static isBlogNode<ThrowOnError extends boolean = false>(options: Options<IsBlogNodeData, ThrowOnError>) {
        return (options.client ?? client).get<IsBlogNodeResponses, IsBlogNodeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/blog/{nodeKey}/is-blog',
            ...options
        });
    }
    
    public static clearSessionizeCache<ThrowOnError extends boolean = false>(options?: Options<ClearSessionizeCacheData, ThrowOnError>) {
        return (options?.client ?? client).post<ClearSessionizeCacheResponses, ClearSessionizeCacheErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/clear-sessionize-cache',
            ...options
        });
    }
    
    public static regenerate<ThrowOnError extends boolean = false>(options?: Options<RegenerateData, ThrowOnError>) {
        return (options?.client ?? client).post<RegenerateResponses, RegenerateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/seed/regenerate',
            ...options
        });
    }
    
    public static status<ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>) {
        return (options?.client ?? client).get<StatusResponses, StatusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/seed/status',
            ...options
        });
    }
}
