// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateHqMemberData, CreateHqMemberErrors, CreateHqMemberResponses, DeleteHqMemberData, DeleteHqMemberErrors, DeleteHqMemberResponses, ExportGitHubDataData, ExportGitHubDataErrors, ExportGitHubDataResponses, GetContributionStatsData, GetContributionStatsErrors, GetContributionStatsResponses, GetHqMemberData, GetHqMemberErrors, GetHqMemberResponses, GetHqMembersData, GetHqMembersErrors, GetHqMembersResponses, GetReleasesData, GetReleasesErrors, GetReleasesResponses, ImportGitHubDataData, ImportGitHubDataErrors, ImportGitHubDataResponses, ImportHqMembersData, ImportHqMembersErrors, ImportHqMembersResponses, ImportSampleGitHubDataData, ImportSampleGitHubDataErrors, ImportSampleGitHubDataResponses, ImportSampleHqMembersData, ImportSampleHqMembersErrors, ImportSampleHqMembersResponses, PingData, PingErrors, PingResponses, UpdateHqMemberData, UpdateHqMemberErrors, UpdateHqMemberResponses, WhatsMyNameData, WhatsMyNameErrors, WhatsMyNameResponses, WhatsTheTimeMrWolfData, WhatsTheTimeMrWolfErrors, WhatsTheTimeMrWolfResponses, WhoAmIData, WhoAmIErrors, WhoAmIResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoCommunityExtensionsService {
    public static getContributionStats<ThrowOnError extends boolean = false>(options?: Options<GetContributionStatsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetContributionStatsResponses, GetContributionStatsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/contributions',
            ...options
        });
    }
    
    public static exportGitHubData<ThrowOnError extends boolean = false>(options?: Options<ExportGitHubDataData, ThrowOnError>) {
        return (options?.client ?? client).get<ExportGitHubDataResponses, ExportGitHubDataErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/export-github-data',
            ...options
        });
    }
    
    public static getHqMembers<ThrowOnError extends boolean = false>(options?: Options<GetHqMembersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetHqMembersResponses, GetHqMembersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers',
            ...options
        });
    }
    
    public static createHqMember<ThrowOnError extends boolean = false>(options?: Options<CreateHqMemberData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateHqMemberResponses, CreateHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteHqMember<ThrowOnError extends boolean = false>(options: Options<DeleteHqMemberData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteHqMemberResponses, DeleteHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers/{id}',
            ...options
        });
    }
    
    public static getHqMember<ThrowOnError extends boolean = false>(options: Options<GetHqMemberData, ThrowOnError>) {
        return (options.client ?? client).get<GetHqMemberResponses, GetHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers/{id}',
            ...options
        });
    }
    
    public static updateHqMember<ThrowOnError extends boolean = false>(options: Options<UpdateHqMemberData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateHqMemberResponses, UpdateHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static importHqMembers<ThrowOnError extends boolean = false>(options?: Options<ImportHqMembersData, ThrowOnError>) {
        return (options?.client ?? client).post<ImportHqMembersResponses, ImportHqMembersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/hqmembers/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static importGitHubData<ThrowOnError extends boolean = false>(options?: Options<ImportGitHubDataData, ThrowOnError>) {
        return (options?.client ?? client).post<ImportGitHubDataResponses, ImportGitHubDataErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/import-github-data',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }    
    public static importSampleGitHubData<ThrowOnError extends boolean = false>(options?: Options<ImportSampleGitHubDataData, ThrowOnError>) {
        return (options?.client ?? client).post<ImportSampleGitHubDataResponses, ImportSampleGitHubDataErrors, ThrowOnError>({
            url: '/umbraco/umbracocommunityextensions/api/v1/import-sample-github-data',
            ...options
        });
    }
    
    public static importSampleHqMembers<ThrowOnError extends boolean = false>(options?: Options<ImportSampleHqMembersData, ThrowOnError>) {
        return (options?.client ?? client).post<ImportSampleHqMembersResponses, ImportSampleHqMembersErrors, ThrowOnError>({
            url: '/umbraco/umbracocommunityextensions/api/v1/import-sample-hq-members',
            ...options
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/ping',
            ...options
        });
    }
    
    public static getReleases<ThrowOnError extends boolean = false>(options?: Options<GetReleasesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetReleasesResponses, GetReleasesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/releases',
            ...options
        });
    }
    
    public static whatsMyName<ThrowOnError extends boolean = false>(options?: Options<WhatsMyNameData, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsMyNameResponses, WhatsMyNameErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/whatsMyName',
            ...options
        });
    }
    
    public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<WhatsTheTimeMrWolfData, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsTheTimeMrWolfResponses, WhatsTheTimeMrWolfErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/whatsTheTimeMrWolf',
            ...options
        });
    }
    
    public static whoAmI<ThrowOnError extends boolean = false>(options?: Options<WhoAmIData, ThrowOnError>) {
        return (options?.client ?? client).get<WhoAmIResponses, WhoAmIErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunityextensions/api/v1/whoAmI',
            ...options
        });
    }
}
