// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44383' | (string & {});
};

export type CreateBlogArticleResponse = {
    articleKey: string;
    articleName: string;
};

export type SessionizeCacheRefreshResult = {
    success: boolean;
    message: string;
    refreshedAt: string;
};

export type SeedExportStatus = {
    isRunning: boolean;
    lastSuccessAt?: string | null;
    lastSuccessSizeBytes?: number | null;
    lastFailureAt?: string | null;
    lastError?: string | null;
    startedAt?: string | null;
};

export type CreateBlogArticleData = {
    body?: never;
    path: {
        blogNodeKey: string;
    };
    query?: never;
    url: '/umbraco/umbracocommunityextensions/api/v1/blog/{blogNodeKey}/create-article';
};

export type CreateBlogArticleErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateBlogArticleResponses = {
    /**
     * Created
     */
    201: CreateBlogArticleResponse;
};

export type CreateBlogArticleResponse2 = CreateBlogArticleResponses[keyof CreateBlogArticleResponses];

export type IsBlogNodeData = {
    body?: never;
    path: {
        nodeKey: string;
    };
    query?: never;
    url: '/umbraco/umbracocommunityextensions/api/v1/blog/{nodeKey}/is-blog';
};

export type IsBlogNodeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type IsBlogNodeResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type IsBlogNodeResponse = IsBlogNodeResponses[keyof IsBlogNodeResponses];

export type RefreshSessionizeCacheData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityextensions/api/v1/sessionize/refresh-cache';
};

export type RefreshSessionizeCacheErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RefreshSessionizeCacheResponses = {
    /**
     * OK
     */
    200: SessionizeCacheRefreshResult;
};

export type RefreshSessionizeCacheResponse = RefreshSessionizeCacheResponses[keyof RefreshSessionizeCacheResponses];

export type RegenerateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityextensions/api/v1/seed/regenerate';
};

export type RegenerateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: SeedExportStatus;
};

export type RegenerateError = RegenerateErrors[keyof RegenerateErrors];

export type RegenerateResponses = {
    /**
     * Accepted
     */
    202: SeedExportStatus;
};

export type RegenerateResponse = RegenerateResponses[keyof RegenerateResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityextensions/api/v1/seed/status';
};

export type StatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type StatusResponses = {
    /**
     * OK
     */
    200: SeedExportStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];
