// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.BlockRestrictions.Infrastructure;

#nullable disable

namespace UmbracoCommunity.BlockRestrictions.Migrations
{
    [DbContext(typeof(BlockRestrictionDbContext))]
    [Migration("20260217141237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("UmbracoCommunity.BlockRestrictions.Infrastructure.BlockRestrictionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AllowedBlockAliasesJson")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("DocumentTypeKey");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeKey")
                        .IsUnique();

                    b.ToTable("BlockRestrictionRules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
