// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.BlockRestrictions.Infrastructure;

#nullable disable

namespace UmbracoCommunity.BlockRestrictions.Migrations
{
    [DbContext(typeof(BlockRestrictionDbContext))]
    partial class BlockRestrictionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("UmbracoCommunity.BlockRestrictions.Infrastructure.BlockRestrictionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedBlockAliasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentTypeKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeKey")
                        .IsUnique();

                    b.ToTable("BlockRestrictionRules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
