// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.Web.Features.GitHubSync.Infrastructure;

#nullable disable

namespace UmbracoCommunity.Web.Migrations
{
    [DbContext(typeof(GitHubDbContext))]
    partial class GitHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.DiscussionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<int>("Number");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RepositoryName", "Number")
                        .IsUnique();

                    b.ToTable("GitHubDiscussions", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.HqMemberEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("GitHubHqMembers", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.IssueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<int>("Number");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RepositoryName", "Number")
                        .IsUnique();

                    b.ToTable("GitHubIssues", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.IssueReleaseEntity", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(100);

                    b.Property<string>("ReleaseLabel")
                        .HasMaxLength(50);

                    b.HasKey("IssueId", "ReleaseLabel");

                    b.HasIndex("ReleaseLabel");

                    b.ToTable("GitHubIssueReleases", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.NuGetPackageVersionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastSyncedAt");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("PublishedDate");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique();

                    b.ToTable("NuGetPackageVersions", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.PullRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<int>("Number");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RepositoryName", "Number")
                        .IsUnique();

                    b.ToTable("GitHubPullRequests", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.PullRequestReleaseEntity", b =>
                {
                    b.Property<string>("PullRequestId")
                        .HasMaxLength(100);

                    b.Property<string>("ReleaseLabel")
                        .HasMaxLength(50);

                    b.HasKey("PullRequestId", "ReleaseLabel");

                    b.HasIndex("ReleaseLabel");

                    b.ToTable("GitHubPullRequestReleases", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.IssueReleaseEntity", b =>
                {
                    b.HasOne("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.IssueEntity", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.PullRequestReleaseEntity", b =>
                {
                    b.HasOne("UmbracoCommunity.Web.Features.GitHubSync.Infrastructure.Entities.PullRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
