using Microsoft.EntityFrameworkCore;

namespace UmbracoCommunity.MeetBooking.Storage;

public class MeetBookingDbContext(DbContextOptions<MeetBookingDbContext> options) : DbContext(options)
{
    public DbSet<MeetProvisioningStateEntity> MeetProvisioningStates { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder) =>
        modelBuilder.Entity<MeetProvisioningStateEntity>(entity =>
        {
            entity.ToTable("MeetProvisioningStates");
            entity.HasKey(e => e.RecordId);
            // The key is the Forms record's UniqueId — always supplied, never generated by the database.
            entity.Property(e => e.RecordId).ValueGeneratedNever();

            // Deliberately unbounded (nvarchar(max) / TEXT): fitting state into a fixed width is the bug this
            // table exists to fix, so don't reintroduce a ceiling here.
            entity.Property(e => e.StateJson).IsRequired();
            entity.Property(e => e.LastError);

            entity.HasIndex(e => e.UpdatedUtc);
        });
}
