// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.BlogAnnouncements.Infrastructure;

#nullable disable

namespace UmbracoCommunity.BlogAnnouncements.Migrations
{
    [DbContext(typeof(BlogAnnouncementsDbContext))]
    partial class BlogAnnouncementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncedBlogPost", b =>
                {
                    b.Property<Guid>("SphereId");

                    b.Property<DateTime?>("AnnouncedUtc");

                    b.Property<string>("AuthorAvatarUrl")
                        .HasMaxLength(2048);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(512);

                    b.Property<string>("AuthorProfileUrl")
                        .HasMaxLength(2048);

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048);

                    b.Property<string>("Excerpt");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<DateTime>("FirstSeenUtc");

                    b.Property<DateTime>("PublishedAtUtc");

                    b.Property<byte>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.HasKey("SphereId");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("AnnouncedBlogPosts", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncementAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AttemptedUtc");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasDefaultValue("Discord");

                    b.Property<int?>("HttpStatus");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<Guid>("SphereId");

                    b.Property<byte>("Trigger");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedUtc");

                    b.HasIndex("SphereId");

                    b.ToTable("AnnouncementAttempts", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncementRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Announced");

                    b.Property<bool>("DryRun");

                    b.Property<int>("Failed");

                    b.Property<int>("Fetched");

                    b.Property<int>("New");

                    b.Property<DateTime>("RunUtc");

                    b.Property<int>("Skipped");

                    b.HasKey("Id");

                    b.HasIndex("RunUtc");

                    b.ToTable("AnnouncementRuns", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncementAttempt", b =>
                {
                    b.HasOne("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncedBlogPost", "Post")
                        .WithMany("Attempts")
                        .HasForeignKey("SphereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UmbracoCommunity.BlogAnnouncements.Models.Entities.AnnouncedBlogPost", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
