// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.MeetBooking.Storage;

#nullable disable

namespace UmbracoCommunity.MeetBooking.Migrations
{
    [DbContext(typeof(MeetBookingDbContext))]
    partial class MeetBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("UmbracoCommunity.MeetBooking.Storage.MeetProvisioningStateEntity", b =>
                {
                    b.Property<Guid>("RecordId");

                    b.Property<string>("LastError");

                    b.Property<string>("StateJson")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedUtc");

                    b.HasKey("RecordId");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("MeetProvisioningStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
