// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.NotFoundTracker.Infrastructure;

#nullable disable

namespace Umbraco.Community.NotFoundTracker.Migrations
{
    [DbContext(typeof(NotFoundTrackerDbContext))]
    partial class NotFoundTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HitCount");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("Hostname", "Path")
                        .IsUnique();

                    b.ToTable("NotFoundHits", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitQueryStringEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("HitId", "QueryString")
                        .IsUnique();

                    b.ToTable("NotFoundHitQueryStrings", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundIgnoreRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hostname", "MatchType", "Path");

                    b.ToTable("NotFoundIgnoreRules", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitQueryStringEntity", b =>
                {
                    b.HasOne("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", "Hit")
                        .WithMany("QueryStrings")
                        .HasForeignKey("HitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hit");
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", b =>
                {
                    b.Navigation("QueryStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
