// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.NotFoundTracker.Infrastructure;

#nullable disable

namespace Umbraco.Community.NotFoundTracker.Migrations
{
    [DbContext(typeof(NotFoundTrackerDbContext))]
    partial class NotFoundTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FirstSeenUtc");

                    b.Property<long>("HitCount");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastSeenUtc");

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(512);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.Property<byte>("Status");

                    b.HasKey("Id");

                    b.HasIndex("HitCount");

                    b.HasIndex("Hostname");

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("NotFoundHits", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitQueryStringEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("HitCount");

                    b.Property<int>("HitId");

                    b.Property<DateTime>("LastSeenUtc");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.HasKey("Id");

                    b.HasIndex("HitId");

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("NotFoundHitQueryStrings", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundIgnoreRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255);

                    b.Property<byte>("MatchType");

                    b.Property<string>("Note")
                        .HasMaxLength(500);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.Property<byte>("Source");

                    b.HasKey("Id");

                    b.HasIndex("Hostname");

                    b.ToTable("NotFoundIgnoreRules", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundPresetSeedRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hostname")
                        .HasMaxLength(255);

                    b.Property<byte>("MatchType");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.Property<DateTime>("SeededUtc");

                    b.HasKey("Id");

                    b.HasIndex("Hostname");

                    b.ToTable("NotFoundPresetSeedRecords", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitQueryStringEntity", b =>
                {
                    b.HasOne("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", "Hit")
                        .WithMany("QueryStrings")
                        .HasForeignKey("HitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hit");
                });

            modelBuilder.Entity("Umbraco.Community.NotFoundTracker.Models.Entities.NotFoundHitEntity", b =>
                {
                    b.Navigation("QueryStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
