// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.Web.Features.Profiles.Data;

#nullable disable

namespace UmbracoCommunity.Web.Features.Profiles.Data.Migrations
{
    [DbContext(typeof(MemberProfilesDbContext))]
    [Migration("20260715203030_AddFeedSource")]
    partial class AddFeedSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberFeedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedUtc");

                    b.Property<bool>("IsHidden");

                    b.Property<bool>("IsRemoved");

                    b.Property<DateTime?>("LastSphereSyncAttemptUtc");

                    b.Property<string>("LastSphereSyncError")
                        .HasMaxLength(1000);

                    b.Property<int>("MemberProfileId");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("RemovedReason")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("RemovedUtc");

                    b.Property<int>("Source");

                    b.Property<int>("SphereSyncStatus");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("MemberFeeds", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AvatarMediaKey");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("GitHubHandle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("MemberKey");

                    b.Property<DateTime?>("OnboardingCompletedUtc");

                    b.Property<DateTime?>("OnboardingStartedUtc");

                    b.Property<int>("OnboardingStatus");

                    b.Property<string>("SphereProfileId")
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedUtc");

                    b.HasKey("Id");

                    b.HasIndex("GitHubHandle");

                    b.HasIndex("MemberKey")
                        .IsUnique();

                    b.ToTable("MemberProfiles", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberFeedEntity", b =>
                {
                    b.HasOne("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", "MemberProfile")
                        .WithMany("Feeds")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", b =>
                {
                    b.Navigation("Feeds");
                });
#pragma warning restore 612, 618
        }
    }
}
