// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbracoCommunity.Web.Features.Profiles.Data;

#nullable disable

namespace UmbracoCommunity.Web.Features.Profiles.Data.Migrations
{
    [DbContext(typeof(MemberProfilesDbContext))]
    partial class MemberProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberFeedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSphereSyncAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSphereSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemovedReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SphereSyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("MemberFeeds", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AvatarMediaKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnboardingCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnboardingStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SphereProfileId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubHandle");

                    b.HasIndex("MemberKey")
                        .IsUnique();

                    b.ToTable("MemberProfiles", (string)null);
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberFeedEntity", b =>
                {
                    b.HasOne("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", "MemberProfile")
                        .WithMany("Feeds")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("UmbracoCommunity.Web.Features.Profiles.Data.Entities.MemberProfileEntity", b =>
                {
                    b.Navigation("Feeds");
                });
#pragma warning restore 612, 618
        }
    }
}
