// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetHqMembersData, GetHqMembersResponses, GetHqMembersErrors, CreateHqMemberData, CreateHqMemberResponses, CreateHqMemberErrors, DeleteHqMemberData, DeleteHqMemberResponses, DeleteHqMemberErrors, GetHqMemberData, GetHqMemberResponses, GetHqMemberErrors, UpdateHqMemberData, UpdateHqMemberResponses, UpdateHqMemberErrors, PingData, PingResponses, PingErrors, WhatsMyNameData, WhatsMyNameResponses, WhatsMyNameErrors, WhatsTheTimeMrWolfData, WhatsTheTimeMrWolfResponses, WhatsTheTimeMrWolfErrors, WhoAmIData, WhoAmIResponses, WhoAmIErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoCommunityGitHubUsers {
    public static getHqMembers<ThrowOnError extends boolean = false>(options?: Options<GetHqMembersData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetHqMembersResponses, GetHqMembersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers',
            ...options
        });
    }
    
    public static createHqMember<ThrowOnError extends boolean = false>(options?: Options<CreateHqMemberData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<CreateHqMemberResponses, CreateHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteHqMember<ThrowOnError extends boolean = false>(options: Options<DeleteHqMemberData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteHqMemberResponses, DeleteHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}',
            ...options
        });
    }
    
    public static getHqMember<ThrowOnError extends boolean = false>(options: Options<GetHqMemberData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetHqMemberResponses, GetHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}',
            ...options
        });
    }
    
    public static updateHqMember<ThrowOnError extends boolean = false>(options: Options<UpdateHqMemberData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<UpdateHqMemberResponses, UpdateHqMemberErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/ping',
            ...options
        });
    }
    
    public static whatsMyName<ThrowOnError extends boolean = false>(options?: Options<WhatsMyNameData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<WhatsMyNameResponses, WhatsMyNameErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/whatsMyName',
            ...options
        });
    }
    
    public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<WhatsTheTimeMrWolfData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<WhatsTheTimeMrWolfResponses, WhatsTheTimeMrWolfErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/whatsTheTimeMrWolf',
            ...options
        });
    }
    
    public static whoAmI<ThrowOnError extends boolean = false>(options?: Options<WhoAmIData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<WhoAmIResponses, WhoAmIErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbracocommunitygithubusers/api/v1/whoAmI',
            ...options
        });
    }
}