// This file is auto-generated by @hey-api/openapi-ts

export type DocumentGranularPermissionModelReadable = {
    key: string;
    readonly context: string;
    permission: string;
};

export type DocumentGranularPermissionModelWritable = {
    key: string;
    permission: string;
};

export type DocumentPropertyValueGranularPermissionModelReadable = {
    key: string;
    readonly context: string;
    permission: string;
};

export type DocumentPropertyValueGranularPermissionModelWritable = {
    key: string;
    permission: string;
};

export type EmploymentPeriod = {
    start?: string | null;
    end?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type GitHubHqMember = {
    id: string;
    login: string;
    name: string;
    periods: Array<EmploymentPeriod>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ReadOnlyUserGroupModelReadable = {
    id: number;
    key: string;
    name: string;
    icon?: string | null;
    startContentId?: number | null;
    startMediaId?: number | null;
    alias: string;
    hasAccessToAllLanguages: boolean;
    allowedLanguages: Array<number>;
    permissions: Array<string>;
    granularPermissions: Array<DocumentGranularPermissionModelReadable | DocumentPropertyValueGranularPermissionModelReadable | UnknownTypeGranularPermissionModel>;
    allowedSections: Array<string>;
};

export type ReadOnlyUserGroupModelWritable = {
    id: number;
    key: string;
    name: string;
    icon?: string | null;
    startContentId?: number | null;
    startMediaId?: number | null;
    alias: string;
    hasAccessToAllLanguages: boolean;
    allowedLanguages: Array<number>;
    permissions: Array<string>;
    granularPermissions: Array<DocumentGranularPermissionModelWritable | DocumentPropertyValueGranularPermissionModelWritable | UnknownTypeGranularPermissionModel>;
    allowedSections: Array<string>;
};

export type UnknownTypeGranularPermissionModel = {
    context: string;
    permission: string;
};

export type UserGroupModelReadable = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    readonly hasIdentity: boolean;
    startMediaId?: number | null;
    startContentId?: number | null;
    icon?: string | null;
    alias: string;
    name?: string | null;
    hasAccessToAllLanguages: boolean;
    permissions: Array<string>;
    granularPermissions: Array<DocumentGranularPermissionModelReadable | DocumentPropertyValueGranularPermissionModelReadable | UnknownTypeGranularPermissionModel>;
    readonly allowedSections: Array<string>;
    readonly userCount: number;
    readonly allowedLanguages: Array<number>;
};

export type UserGroupModelWritable = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    startMediaId?: number | null;
    startContentId?: number | null;
    icon?: string | null;
    alias: string;
    name?: string | null;
    hasAccessToAllLanguages: boolean;
    permissions: Array<string>;
    granularPermissions: Array<DocumentGranularPermissionModelWritable | DocumentPropertyValueGranularPermissionModelWritable | UnknownTypeGranularPermissionModel>;
};

export enum UserKindModel {
    DEFAULT = 'Default',
    API = 'Api'
}

export type UserModelReadable = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    readonly hasIdentity: boolean;
    emailConfirmedDate?: string | null;
    invitedDate?: string | null;
    username: string;
    email: string;
    rawPasswordValue?: string | null;
    passwordConfiguration?: string | null;
    isApproved: boolean;
    isLockedOut: boolean;
    lastLoginDate?: string | null;
    lastPasswordChangeDate?: string | null;
    lastLockoutDate?: string | null;
    failedPasswordAttempts: number;
    comments?: string | null;
    userState: UserStateModel;
    name?: string | null;
    readonly allowedSections: Array<string>;
    profileData: UserModelReadable | UserProfileModel;
    securityStamp?: string | null;
    avatar?: string | null;
    sessionTimeout: number;
    startContentIds?: Array<number> | null;
    startMediaIds?: Array<number> | null;
    language?: string | null;
    kind: UserKindModel;
    readonly groups: Array<ReadOnlyUserGroupModelReadable | UserGroupModelReadable>;
};

export type UserModelWritable = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    emailConfirmedDate?: string | null;
    invitedDate?: string | null;
    username: string;
    email: string;
    rawPasswordValue?: string | null;
    passwordConfiguration?: string | null;
    isApproved: boolean;
    isLockedOut: boolean;
    lastLoginDate?: string | null;
    lastPasswordChangeDate?: string | null;
    lastLockoutDate?: string | null;
    failedPasswordAttempts: number;
    comments?: string | null;
    userState: UserStateModel;
    name?: string | null;
    profileData: UserModelWritable | UserProfileModel;
    securityStamp?: string | null;
    avatar?: string | null;
    sessionTimeout: number;
    startContentIds?: Array<number> | null;
    startMediaIds?: Array<number> | null;
    language?: string | null;
    kind: UserKindModel;
};

export type UserProfileModel = {
    id: number;
    name?: string | null;
};

export enum UserStateModel {
    ACTIVE = 'Active',
    DISABLED = 'Disabled',
    LOCKED_OUT = 'LockedOut',
    INVITED = 'Invited',
    INACTIVE = 'Inactive',
    ALL = 'All'
}

export type GetHqMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers';
};

export type GetHqMembersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetHqMembersResponses = {
    /**
     * OK
     */
    200: Array<GitHubHqMember>;
};

export type GetHqMembersResponse = GetHqMembersResponses[keyof GetHqMembersResponses];

export type CreateHqMemberData = {
    body?: GitHubHqMember;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers';
};

export type CreateHqMemberErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateHqMemberResponses = {
    /**
     * Created
     */
    201: GitHubHqMember;
};

export type CreateHqMemberResponse = CreateHqMemberResponses[keyof CreateHqMemberResponses];

export type DeleteHqMemberData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}';
};

export type DeleteHqMemberErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteHqMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteHqMemberResponse = DeleteHqMemberResponses[keyof DeleteHqMemberResponses];

export type GetHqMemberData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}';
};

export type GetHqMemberErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetHqMemberResponses = {
    /**
     * OK
     */
    200: GitHubHqMember;
};

export type GetHqMemberResponse = GetHqMemberResponses[keyof GetHqMemberResponses];

export type UpdateHqMemberData = {
    body?: GitHubHqMember;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/hqmembers/{id}';
};

export type UpdateHqMemberErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateHqMemberResponses = {
    /**
     * OK
     */
    200: GitHubHqMember;
};

export type UpdateHqMemberResponse = UpdateHqMemberResponses[keyof UpdateHqMemberResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type WhatsMyNameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/whatsMyName';
};

export type WhatsMyNameErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type WhatsMyNameResponses = {
    /**
     * OK
     */
    200: string;
};

export type WhatsMyNameResponse = WhatsMyNameResponses[keyof WhatsMyNameResponses];

export type WhatsTheTimeMrWolfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/whatsTheTimeMrWolf';
};

export type WhatsTheTimeMrWolfErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type WhatsTheTimeMrWolfResponses = {
    /**
     * OK
     */
    200: string;
};

export type WhatsTheTimeMrWolfResponse = WhatsTheTimeMrWolfResponses[keyof WhatsTheTimeMrWolfResponses];

export type WhoAmIData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitygithubusers/api/v1/whoAmI';
};

export type WhoAmIErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type WhoAmIResponses = {
    /**
     * OK
     */
    200: UserModelReadable;
};

export type WhoAmIResponse = WhoAmIResponses[keyof WhoAmIResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44383' | (string & {});
};