name: pipeline

# Trigger when committing to main branch
on:
  push:
    branches:
     - main

env:
  deployLicenseKey: ${{ secrets.deployLicenseKey }}
  formsLicenseKey: ${{ secrets.formsLicenseKey }}
  umbracoCloudJson: ${{ secrets.umbracoCloudJson }}
  pathToWebsite: "src/UmbracoCommununity.Web.UI"

jobs:

  # Intentionally NOT syncing from Cloud as all patches/updates etc being done manually on GitHub repo

  # Replace the private files needed by Cloud from GitHub secrets
  reset-private-files:
    name: Test Private Files for Umbraco Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        working-directory: ${{env.pathToWebsite}}
        shell: pwsh
        run: set-content 'umbraco-cloud.txt' -value "Hello World"

  # Package and Deploy to Umbraco Cloud
  #cloud-deployment:
  #  uses: ./.github/workflows/cloud-deployment.yml
  #  secrets:
  #    projectId: ${{ secrets.PROJECT_ID }}
  #   umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
