name: pipeline

# Trigger when committing to main branch
on:
  push:
    branches:
     - main

env:
  deployLicenseKey: ${{ secrets.deployLicenseKey }}
  formsLicenseKey: ${{ secrets.formsLicenseKey }}
  umbracoCloudJson: ${{ secrets.umbracoCloudJson }}

jobs:

  # Intentionally NOT syncing from Cloud as all patches/updates etc being done manually on GitHub repo

  # Replace the private files needed by Cloud from GitHub secrets
  reset-private-files:
    name: Reset Private Files for Umbraco Cloud
    runs-on: ubuntu-latest
    steps:

      # Testing with simple text.txt
      name: Test
      shell: pwsh
      run: >
        ${{GITHUB.WORKSPACE}}/.github/powershell/Replace-File-Contents.ps1 
        -FolderPath '${{GITHUB.WORKSPACE}}'
        -FileName 'text.txt'
        -FileContents 'test string'

  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    needs: reset-private-files
    uses: ./.github/workflows/cloud-deployment.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
